### ISSUE TITLE
Fails in a mashup

### ISSUE THREAD

**Issue by celindho** [bohua/nprinting-sense-on-demand#10]
If the extension is added to a mashup, it does not work. Apparently the websocket is opened to the address of the extension and not the app.

**Comment by bohua** [comment]
HI Christian,

Sorry for late reply, it sounds weird coz Nprinting extension is not using
any websocket to communicate to NP server. The only only change to involve
websocket is to collect current selections.  I will have a look into this!
Probably after new year since it's a busy period.  :)  Please feel free to
contact me if things get urgent for you.

Brs,
//Bohua

2017-12-15 15:21 GMT+01:00 Christian Lindholm <notifications@github.com>:

**Comment by celindho** [comment]
Hi,

Thanks for the reply! Based on my debugging effort, it appears to crash exactly when fetching the current selections. We have managed to figure out a workaround that should reduce the urgency of this problem but does not help with the original issue of getting it to work inside the mashup. I would none the less still appreciate any effort in looking into this bug :)

Br
-Christian

**Comment by safaGued** [comment]
Hello @celindho @bohua ,

I have the same problem when using the mashup.
The extension is working in the QS app in the hub but not with the mashup.
@celindho : Could you please tell me what was your workaround for this issue? I must find an urgent solution

Thank you in advance 
Regards

**Comment by celindho** [comment]
@safaGued, in the mashup i added a link to the main document to a sheet where the button exists. If you make sure that the link opens in a new tab, the current selection will still ve active. The nprinting button works this way.

**Comment by safaGued** [comment]
Thank you a lot for your quick answer.
I will try your solution and come back to you ;)

**Comment by sgandotr** [comment]
@celindho where are you adding the link? Are you opening an app in another tab?

**Comment by bohua** [comment]
Hi @celindho @safaGued 

With the latest fix with Capability API, the problem should be resolved in mashups, since the selections are not pending on internal Qlik modules any more!

**Comment by celindho** [comment]
Thanks for the info. I'll test this out next time I have the chance :)
