### ISSUE TITLE
Unable to connect to NPrinting Server without refreshing Qlik Sense Hub

### ISSUE THREAD

**Issue by abhatkargp** [bohua/nprinting-sense-on-demand#12]
This is a really useful extension. Thank you for that!

I have an issue with the server connection. When I drag and drop the extension on a sheet and enter the address in the server connection field, the apps drop-down does not get populated. However, it does get populated after refreshing the page; meaning Qlik Sense Hub is able to connect to NPrinting Server, just not when I enter the proxy address in the server connection field for the first time.

Can this be done without having to refresh the page?

I have attached the following screenshots: 
Screenshot 1 - Web console error messages screenshot before refreshing the page.
Screenshot 2,3,4 - "Get" method expanded.
Screenshot 5 - With Apps drop-down populated
[Screenshots_refresh_for_apps_dropdown.pdf](https://github.com/bohua/nprinting-sense-on-demand/files/1813627/Screenshots_refresh_for_apps_dropdown.pdf)

It would be great if you could help me in this issue

Regards,
Akshay Bhatkar

**Comment by bohua** [comment]
Hi Akshay,

It looks strange that it doesn't work for the first time and get a 403 permissions deny. I didn't have this problem reproduced. Could you provide your QS and NP versions?

//Bohua

**Comment by bohua** [comment]
close due to no response
