### ISSUE TITLE
No download button showing

### ISSUE THREAD

**Issue by kalmirall** [bohua/nprinting-sense-on-demand#13]
Hi there!  This was working briefly, but now when I as an admin or any of my users try to download a report, it generates, but there is no download button.  Any ideas on what may be happening?

**Comment by bohua** [comment]
Hi! Sorry for the late reply. Is that still a problem for you? Or could you provide a snapshot of the issue?

**Comment by bohua** [comment]
close due to no response

**Comment by kalmirall** [comment]
Hi Bohua!  Sorry for the lack of response, I just got back from vacation.  I never did get this working, but we pursued other solutions.  I’ll let you know if we try this again in the future.
