### ISSUE TITLE
Usage of unsupported modules will fail in June 2018

### ISSUE THREAD

**Issue by mindspank** [bohua/nprinting-sense-on-demand#14]
Hey,

This extension relies on Qlik internal, un-documented modules such as `objects.backend-api/listbox-api`, `objects.models/listbox` which will no longer be available in the June 2018 release.

We can temporarily allow usage of some of them but long-term we would wish to move this onto a supported codebase. Viewing the source of the extension most of the usage of un-supported modules can be replaced by supported functionality provided via the Capabilities API.

We are happy to help you move this into a supported scenario, feel free to ping me on akl at qlik dot com or join us on slack http://branch.qlik.com/slack

**Comment by bohua** [comment]
Problem fixed with Capability API adaptions in code
