### ISSUE TITLE
Not working in initial QS June 2018 release?

### ISSUE THREAD

**Issue by jfortner03** [bohua/nprinting-sense-on-demand#15]
Hi Bohua,

It seems that this extension doesn't work in the initial June 2018 release? I installed June 2018 and am seeing an error on the object, "Invalid Visualization: The visualization was not found on the server: nprinting-sense-on-demand". Thoughts?

**Comment by bohua** [comment]
HI Josh,

Thanks for reminding. I also got noticed by many other clients. I will do a
quick investigation as soon as I come back on 12th July.

Best regards,
//Bohua

2018-06-29 19:21 GMT+02:00 jfortner03 <notifications@github.com>:

**Comment by bohua** [comment]
Problem fixed with Capability API adaptions in code

**Comment by bohua** [comment]
Problem fixed with Capability API adaptions in code

**Comment by jfortner03** [comment]
Thanks for the response. Does this mean that June 2018 Patch 1 has been released? I don’t see it on the Qlik site.

Regards,

Josh Fortner
Product Manager of Business Intelligence, Information Technology
2001 Riverside Drive ▪ Chattanooga, TN  37406
Office: 423.643.3249
Cell: 423.362.6699
https://www.gotomeet.me/JFortner

[Description: Description: Description: Description: cid:425B3975-0433-499C-8AAA-3DA8695B7F42]<http://kencogroup.com/>
The information contained in this electronic communication and any accompanying document is confidential and is intended only for the use of the addressee.  Unauthorized use, disclosure or copying of this communication, or any part of it, is strictly prohibited and may be unlawful.  If you have received this communication in error, please notify the sender immediately by return email, and destroy this communication and all copies of it, including all attachments.

**Comment by bohua** [comment]
Hi Josh,

No, it’s not release. I just changed the code in the extension to use Qlik Capability API for fetching selection data instead of using internal modules. You only need to download the latest extension and it should work now with any Qlik version.

Regards,
//bohua

**Comment by jfortner03** [comment]
Wonderful thanks!

Regards,

Josh Fortner
Product Manager of Business Intelligence, Information Technology
2001 Riverside Drive ▪ Chattanooga, TN  37406
Office: 423.643.3249
Cell: 423.362.6699
https://www.gotomeet.me/JFortner

[Description: Description: Description: Description: cid:425B3975-0433-499C-8AAA-3DA8695B7F42]<http://kencogroup.com/>
The information contained in this electronic communication and any accompanying document is confidential and is intended only for the use of the addressee.  Unauthorized use, disclosure or copying of this communication, or any part of it, is strictly prohibited and may be unlawful.  If you have received this communication in error, please notify the sender immediately by return email, and destroy this communication and all copies of it, including all attachments.
