### ISSUE TITLE
IE extension not visible

### ISSUE THREAD

**Issue by lilianvallon** [bohua/nprinting-sense-on-demand#17]
Hi,
I can't see the extension or use it with IE 11. It works great with chrome and firefox but my users only have IE. I tried to debug my application web page which use the extension. The debugger have found an error in the file nprinting-sense-on-demand.js, on line 30, col 5.
I have inspected the file and found that the last element line 27 : Deferred,
I have remove the comma (last element on a list) and the extension work. I have some minor graphics bug but it works. Is it a real bug or do i have make a wrong modification?

**Comment by bohua** [comment]
hi @lilianvallon, 

Thank you for your inputs. You are right, IE11 does not support extra comma in objects since it doesn't support ES6 yet. I will fix that in the code. 👍
