### ISSUE TITLE
Not Generated Report 

### ISSUE THREAD

**Issue by Rut16** [bohua/nprinting-sense-on-demand#2]
Hello
        I clicked on Report button but pop-up not show and not generated any on-demand reports.

**Comment by bohua** [comment]
Hi  @Rut16 ,

Sorry for a late reply. Would you please confirm if it's still an issue for you? Otherwise, please provide info around QS/NP versions, browser version and corresponding snapshots, thanks!

**Comment by bohua** [comment]
close due to no response
