### ISSUE TITLE
Using On-Demand not over port 4993

### ISSUE THREAD

**Issue by amien90** [bohua/nprinting-sense-on-demand#26]
https://nprinting.test.local:4993/

4993 is blocked for us. So we creating a routing from https://nprinting.test.local/nprinting/ to https://nprinting.test.local:4993/
First one is 443 and this is allowed.

But now On-Demand is not working. I can connect. I see the reports. When i want to use it, i get the NTML pop-up and i can login. But after this, nothing happens.

Is anyone aware of any additional changes i need to do to make https://nprinting.test.local/nprinting/ work?

Thanks in advanced

**Comment by amien90** [comment]
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Forbidden</title>
	</head>
	<body>
	
	<h1>
		Forbidden
	</h1>
	<p>
		REVEL_CSRF: tokens mismatch.
	</p>
	
	</body>
</html>


This is the error

**Comment by and29** [comment]
Hi @amien90,
have you tried to change the port configuration of Nprinting?
You can do it from configuration file: 
 `ProgramData\NPrinting\webconsoleproxy\app.conf`
by uncommenting "http.port=4993" and changing the port number (you need to restart the engine service to see the change).
So you can try to authenticate directly to the proxy on the new port and see if it works.

Andrea

**Comment by amien90** [comment]
"http.port=4993" is uncommented.

The problem seems to be that the Application gateway of Azure if not respecting (and removed) the custom entry X-XSRF-TOKEN. I will check if this can be fixed.

**Comment by and29** [comment]
can you also change the port value, setting it to an open port you can use in your environment?

**Comment by amien90** [comment]
we went for white listing port 4993

**Comment by amien90** [comment]
there were not other ports open.
using 443 was not possible because it runs on the same domain as Qlik Sense and there 443 was already taken.
