### ISSUE TITLE
Doesn't Work in Firefox?

### ISSUE THREAD

**Issue by jfortner03** [bohua/nprinting-sense-on-demand#7]
Hello, I've tried the NPrinting Button in Firefox, and it doesn't seem to work. I'm using Qlik Sense June 2017 Patch 1, NPrinting June 2017. I was able to get this to work in Chrome after adding the Qlik Sense URL as a trusted source in NPrinting, but tried the button in Firefox, and nothing happens. I opened the console and don't see any messages at all when I press the button.

**Comment by bohua** [comment]
hi @jfortner03 

Sorry for a late reply. Could you confirm it the problem remains?

**Comment by bohua** [comment]
close due to no response
