### ISSUE TITLE
Multiple connections in one NPrinting app

### ISSUE THREAD

**Issue by jpitchford** [bohua/nprinting-sense-on-demand#9]
I'm using Qlik Sense June 2017 and Qlik NPrinting June 2017 and the extension works great. I Just wanted to raise the point that it doesn't work for multiple nprinting connections in one nprinting app. it still generates a report without selections being made. but when with selections, the report isn't generated.

thanks for the great extension though

**Comment by bohua** [comment]
Thank you for your message. We do notice this defect from multiple clients. I will fix this ASAP. 

Bohua Li

**Comment by gkrish26** [comment]
Hi Bohua,

Can you please let us know when can we expect a solution for this issue??

Regards,
kkrish26

**Comment by gkrish26** [comment]
@bohua is there any update on this issue ?? this fix will save most of our issues.

**Comment by bohua** [comment]
hi @gkrish26 

Sorry for a later reply. Could you confirm if the problem still there?

**Comment by gkrish26** [comment]
@bohua 
yes. still the issue exists.

**Comment by bohua** [comment]
@gkrish26 @jpitchford Problem reproduced and finally fixed

**Comment by gkrish26** [comment]
@bohua that means we need to import new  updated extension or do we need to update code in some where ??

**Comment by bohua** [comment]
You just need to download the latest code and re-impor the extensions to QMC, then it works.

**Comment by gkrish26** [comment]
@bohua Thank you.
